### ISSUE TITLE
[PE-D][Tester D] Different color for success message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W13-2/tp#131]
![image.png](https://raw.githubusercontent.com/tanyunchao/ped/main/files/f70ef33d-b2df-4504-a497-239019c720d8.png)

- difference in font color of success message between the screenshot provided on the UG vs the actual product

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: tanyunchao/ped#4

**Comment by Derekljh** [comment]
fixed
