### ISSUE TITLE
[PE-D][Tester D] wrong example for invalid phone command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W13-2/tp#148]
-
![image.png](https://raw.githubusercontent.com/tanyunchao/ped/main/files/e048d3ac-33d9-4574-8fa2-0f97d6b4b97f.png)

example given seems to be in the wrong format as well

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tanyunchao/ped#10

**Comment by Derekljh** [comment]
fixed
