### ISSUE TITLE
Use case: Viewing add contacts

### ISSUE THREAD

**Issue by miffi** [AY2324S2-CS2103T-W13-2/tp#22]

**Comment by The-Dudeski** [comment]
System: OfficeHarbour (OH)
Use case: Viewing Contacts
Actor: Secretary
MSS:
  1. Secretary decides add a new contact to the system
  2. Contact will be displayed in a sidebar
  3. Contact can be selected for deletion
  Use case ends.

**Comment by miffi** [comment]
uhh you're supposed to PR this to the DeveloperGuide.md in `docs/`
